name: IssueTracker deployment

run-name: Deployment ${{ github.run_number }} by ${{ github.actor }}

on: 
  # push: 
  #   branches: ["main"]
  pull_request: 
    branches: 
      - 'main'
    types: 
      - closed # the if statement in the deployment job makes sure that this only applies to pull requests that are merged into main

jobs: 
  deployment: 
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true 
    permissions:
      packages: write
    steps: 
      - name: Checkout
        uses: actions/checkout@v4

      - name: Save values to environment
        run: | 
          echo "GIT_REPO=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo "GIT_SHA=$(echo '${{ github.sha }}' | cut -c1-10)" >> $GITHUB_ENV

      - name: Login to GitHub
        uses: docker/login-action@v3
        with: 
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with: 
          context: .
          push: true
          file: ./src/IssueTracker.MVC/Dockerfile
          tags: |
            ghcr.io/${{ env.GIT_REPO }}:latest 
            ghcr.io/${{ env.GIT_REPO }}:${{ github.run_number }}-${{ env.GIT_SHA }}
